data:extend({
  { type = "fluid", name = "photoresist",
    default_temperature = 15,
    heat_capacity = "0KJ",
    base_color = {r=0.4, g=0, b=0.4},
    flow_color = {r=0.5, g=0.5, b=0.5},
    max_temperature = 100,
    icon = "__CartmenElectronics__/graphics/icons/fluid/photoresist.png",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  
  { type = "fluid", name = "liquid-silicon",
    default_temperature = 1200,
	max_temperature = 1200,
	heat_capacity = "0KJ",
	base_color = {r=83, g=83, b=84},
    flow_color = {r=83, g=83, b=84},
	icon = "__CartmenElectronics__/graphics/icons/fluid/liquid-silicon.png",
	subgroup = "ci-chemicals",
	order = "b",
	pressure_to_speed_ratio = 0.4,
	flow_to_energy_ratio = 0.59,
  },
  
  { type = "fluid", name = "epoxy",
    default_temperature = 15,
    heat_capacity = "0KJ",
    base_color = {r=0.4, g=0, b=0.4},
    flow_color = {r=0.5, g=0.5, b=0.5},
    max_temperature = 100,
    icon = "__CartmenElectronics__/graphics/icons/fluid/epoxy.png",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  
  { type = "fluid", name = "bisphenol",
    default_temperature = 15,
    heat_capacity = "0KJ",
    base_color = {r=0.4, g=0, b=0.4},
    flow_color = {r=0.5, g=0.5, b=0.5},
    max_temperature = 100,
    icon = "__CartmenElectronics__/graphics/icons/fluid/bisphenol.png",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  
  { type = "fluid", name = "epichlorohydrin",
    default_temperature = 15,
    heat_capacity = "0KJ",
    base_color = {r=0.4, g=0, b=0.4},
    flow_color = {r=0.5, g=0.5, b=0.5},
    max_temperature = 100,
    icon = "__CartmenElectronics__/graphics/icons/fluid/epichlorohydrin.png",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  
  { type = "fluid", name = "allyl-chloride",
    default_temperature = 15,
    heat_capacity = "0KJ",
    base_color = {r=0.4, g=0, b=0.4},
    flow_color = {r=0.5, g=0.5, b=0.5},
    max_temperature = 100,
    icon = "__CartmenElectronics__/graphics/icons/fluid/allyl-chloride.png",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  
  { type = "fluid", name = "hypochlorous-acid",
    default_temperature = 15,
    heat_capacity = "0KJ",
    base_color = {r=0.4, g=0, b=0.4},
    flow_color = {r=0.5, g=0.5, b=0.5},
    max_temperature = 100,
    icon = "__CartmenElectronics__/graphics/icons/fluid/hypochlorous-acid.png",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
})